git:
  submodules: false
language: scala
sudo: required
services:
  - docker
cache:
  directories:
    $HOME/.ivy2
    emulator/verilator

env:
  global:
    - CACHE_NAME=RocketChip
    - RISCV=/opt/riscv
    - TORTURE_CONFIG=default
  matrix:
    - SUITE=RocketSuiteA
    - SUITE=RocketSuiteB
    - SUITE=RocketSuiteC
    - SUITE=GroundtestSuiteA
    - SUITE=GroundtestSuiteB
    - SUITE=UnittestSuite

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

install:
  - make verilator -C regression SUITE=none

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8
  - docker pull hcook/docker-riscv
  - docker ps -a
  - docker run hcook/docker-riscv

script:
  - make emulator-ndebug -C regression SUITE=$SUITE 
  - make emulator-regression-tests -C regression SUITE=$SUITE
