git:
  submodules: false
language: scala
sudo: required
services:
  - docker

env:
  matrix:
    - SUITE=RocketSuite
    - SUITE=GroundtestSuite
    - SUITE=UnittestSuite

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

before_install:
  - docker pull hcook/docker-riscv:chisel

script:
  - docker run -v /home/travis/build/ucb-bar/rocket-chip:/opt/riscv/test hcook/docker-riscv:chisel /bin/sh -c  "touch /usr/local/bin/verilator; make emulator-ndebug -C regression SUITE=$SUITE; make emulator-regression-tests -C regression SUITE=$SUITE"
