git:
  submodules: false
language: scala
sudo: required
services:
  - docker
cache:
  directories:
    $HOME/.ivy2
    emulator/verilator

env:
  global:
    - CACHE_NAME=RocketChip
    - RISCV=/opt/riscv
    - TORTURE_CONFIG=default
  matrix:
    - SUITE=RocketSuiteA
    - SUITE=RocketSuiteB
    - SUITE=RocketSuiteC
    - SUITE=GroundtestSuiteA
    - SUITE=GroundtestSuiteB
    - SUITE=UnittestSuite

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

install:
  - make verilator -C regression SUITE=none

before_install:
  - docker pull hcook/docker-riscv

script:
  - docker run -v /home/travis/build/ucb-bar/rocket-chip:/opt/riscv/test hcook/docker-riscv /bin/sh -c  "which verilator; make emulator-ndebug -C regression SUITE=$SUITE; make emulator-regression-tests -C regression SUITE=$SUITE" 
