git:
  submodules: false
language: scala
sudo: required
services:
  - docker

env:
  matrix:
    - SUITE=RocketSuiteA
    - SUITE=RocketSuiteB
    - SUITE=RocketSuiteC
    - SUITE=GroundtestSuiteA
    - SUITE=GroundtestSuiteB
    - SUITE=UnittestSuite

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

before_install:
  - docker pull hcook/docker-riscv:chisel

script:
  - docker run -v $(pwd):/opt/riscv/test hcook/docker-riscv:chisel /bin/sh -c  "make emulator-ndebug -C regression SUITE=$SUITE; make emulator-regression-tests -C regression SUITE=$SUITE"
