name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  check-wit:
    name: Check Wit Manifest
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: ci-tests/check_submodules
